driver:
  browser: 'chrome'
  driver_path: '/usr/bin/chromedriver'
  options:
  - '--no-sandbox'
  - '--disable-dev-shm-usage'
  - '--disable-gpu'
  - 'blink-settings=imagesEnabled=false'
  - '--headless'
  - 'window-size=1920x1080'
runtime:
  mode: 'auto'
  log: false
  cmdout: true
yysmart:
  resource_path: ''
  user_profile_path: ''
