driver:
  browser: 'edge'
  driver_path: 'C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe'
  options: []
runtime:
  cmdout: false
  log: true
  mode: 'check'
yysmart:
  resource_path: ''
  user_profile_path: ''
