driver:
  browser: 'edge'
  driver_path: 'C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe'
  options: []
runtime:
  cmdout: false
  log: true
  mode: 'exam'
yysmart:
  resource_path: 'C:\Users\[user-name]\Documents\GMP\YYsmart'
  user_profile_path: 'C:\Users\[user-name]\AppData\Roaming\YYsmartWeb'
