driver:
  browser: 'edge'
  driver_path: 'C:\Users\lucien\AppData\Local\Programs\selenium_driver\edge\103.0.1264.37\msedgedriver.exe'
  options: []
  wait_interval: 0.5
runtime:
  cmdout: false
  log: true
  mode: 'auto'
yysmart:
  resource_path: ''
  user_profile_path: ''
