name: GMP Auto
on:
  workflow_dispatch:
jobs:
  auto_complete:
    name: Auto Complete
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with: 
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./dependencies/requirements.txt
        sudo cp -p ./settings_profiles/settings_auto_github_workflow.yaml ./settings.yaml
    - name: GMP Auto Complete
      run: |
        python ./multi_stu.py
